// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLDuAnPhanMemTinHoc.Data;

#nullable disable

namespace QLDuAnPhanMemTinHoc.Migrations
{
    [DbContext(typeof(QLDADbContext))]
    partial class QLDADbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.Bug", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DuAnID")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBaoCao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiBaoCaoID")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiXuLyID")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DuAnID");

                    b.HasIndex("NguoiBaoCaoID");

                    b.HasIndex("NguoiXuLyID");

                    b.ToTable("Bug");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.CongViec", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DoUuTien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuAnID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("HanHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenCongViec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DuAnID");

                    b.ToTable("CongViec");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.DuAn", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuanLyID")
                        .HasColumnType("int");

                    b.Property<string>("TenDuAn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("QuanLyID");

                    b.ToTable("DuAn");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.KhachHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("QuyenHan")
                        .HasColumnType("bit");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.NhanVien_VaiTro", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<int>("VaiTroID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID");

                    b.HasIndex("VaiTroID");

                    b.ToTable("NhanVien_VaiTro");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.NhatKyHoatDong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MoTaHoatDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("NhatKyHoatDong");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.PhanCong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DuAnID")
                        .HasColumnType("int");

                    b.Property<int?>("DuAnID1")
                        .HasColumnType("int");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<int?>("NhanVienID1")
                        .HasColumnType("int");

                    b.Property<string>("VaiTroTrongDuAn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DuAnID");

                    b.HasIndex("DuAnID1");

                    b.HasIndex("NhanVienID");

                    b.HasIndex("NhanVienID1");

                    b.ToTable("PhanCong");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.PhanCongCongViec", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CongViecID")
                        .HasColumnType("int");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CongViecID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("PhanCongCongViec");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.TaiLieuDuAn", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DuAnID")
                        .HasColumnType("int");

                    b.Property<string>("DuongDan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTaiLen")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenTaiLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DuAnID");

                    b.ToTable("TaiLieuDuAn");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.TienDo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CongViecID")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanTram")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CongViecID");

                    b.ToTable("TienDo");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.VaiTro", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.Bug", b =>
                {
                    b.HasOne("QLDuAnPhanMemTinHoc.Data.DuAn", "DuAn")
                        .WithMany("Bug")
                        .HasForeignKey("DuAnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLDuAnPhanMemTinHoc.Data.NhanVien", "NguoiBaoCao")
                        .WithMany("BugBaoCao")
                        .HasForeignKey("NguoiBaoCaoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLDuAnPhanMemTinHoc.Data.NhanVien", "NguoiXuLy")
                        .WithMany("BugXuLy")
                        .HasForeignKey("NguoiXuLyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DuAn");

                    b.Navigation("NguoiBaoCao");

                    b.Navigation("NguoiXuLy");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.CongViec", b =>
                {
                    b.HasOne("QLDuAnPhanMemTinHoc.Data.DuAn", "DuAn")
                        .WithMany("CongViec")
                        .HasForeignKey("DuAnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuAn");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.DuAn", b =>
                {
                    b.HasOne("QLDuAnPhanMemTinHoc.Data.KhachHang", "KhachHang")
                        .WithMany("DuAn")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLDuAnPhanMemTinHoc.Data.NhanVien", "QuanLy")
                        .WithMany("DuAnQuanLy")
                        .HasForeignKey("QuanLyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("QuanLy");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.NhanVien_VaiTro", b =>
                {
                    b.HasOne("QLDuAnPhanMemTinHoc.Data.NhanVien", "NhanVien")
                        .WithMany("NhanVien_VaiTro")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLDuAnPhanMemTinHoc.Data.VaiTro", "VaiTro")
                        .WithMany("NhanVien_VaiTro")
                        .HasForeignKey("VaiTroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.NhatKyHoatDong", b =>
                {
                    b.HasOne("QLDuAnPhanMemTinHoc.Data.NhanVien", "NhanVien")
                        .WithMany("NhatKyHoatDong")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.PhanCong", b =>
                {
                    b.HasOne("QLDuAnPhanMemTinHoc.Data.DuAn", "DuAn")
                        .WithMany("PhanCongs")
                        .HasForeignKey("DuAnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLDuAnPhanMemTinHoc.Data.DuAn", null)
                        .WithMany("PhanCong")
                        .HasForeignKey("DuAnID1");

                    b.HasOne("QLDuAnPhanMemTinHoc.Data.NhanVien", "NhanVien")
                        .WithMany("PhanCongs")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QLDuAnPhanMemTinHoc.Data.NhanVien", null)
                        .WithMany("PhanCong")
                        .HasForeignKey("NhanVienID1");

                    b.Navigation("DuAn");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.PhanCongCongViec", b =>
                {
                    b.HasOne("QLDuAnPhanMemTinHoc.Data.CongViec", "CongViec")
                        .WithMany("PhanCongCongViec")
                        .HasForeignKey("CongViecID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLDuAnPhanMemTinHoc.Data.NhanVien", "NhanVien")
                        .WithMany("PhanCongCongViec")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CongViec");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.TaiLieuDuAn", b =>
                {
                    b.HasOne("QLDuAnPhanMemTinHoc.Data.DuAn", "DuAn")
                        .WithMany("TaiLieuDuAn")
                        .HasForeignKey("DuAnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuAn");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.TienDo", b =>
                {
                    b.HasOne("QLDuAnPhanMemTinHoc.Data.CongViec", "CongViec")
                        .WithMany("TienDo")
                        .HasForeignKey("CongViecID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongViec");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.CongViec", b =>
                {
                    b.Navigation("PhanCongCongViec");

                    b.Navigation("TienDo");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.DuAn", b =>
                {
                    b.Navigation("Bug");

                    b.Navigation("CongViec");

                    b.Navigation("PhanCong");

                    b.Navigation("PhanCongs");

                    b.Navigation("TaiLieuDuAn");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.KhachHang", b =>
                {
                    b.Navigation("DuAn");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.NhanVien", b =>
                {
                    b.Navigation("BugBaoCao");

                    b.Navigation("BugXuLy");

                    b.Navigation("DuAnQuanLy");

                    b.Navigation("NhanVien_VaiTro");

                    b.Navigation("NhatKyHoatDong");

                    b.Navigation("PhanCong");

                    b.Navigation("PhanCongCongViec");

                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("QLDuAnPhanMemTinHoc.Data.VaiTro", b =>
                {
                    b.Navigation("NhanVien_VaiTro");
                });
#pragma warning restore 612, 618
        }
    }
}
